//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssingnmentRegistration.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int CustomerID { get; set; }
        public string CustomerName { get; set; }
        public Nullable<decimal> CurrentBalanace { get; set; }
        public Nullable<decimal> NetBalance { get; set; }
    }
}
